services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: servicelab
      POSTGRES_USER: servicelab
      POSTGRES_PASSWORD: servicelab
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fleetpulse"]
      interval: 5s

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  prometheus:
    image: prom/prometheus:latest
    volumes: ["./prometheus.yml:/etc/prometheus/prometheus.yml:ro"]
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    ports: ["3000:3000"]
